// Self-host the site's photography. Reads every Unsplash photo id referenced in
// src/lib/site.ts, downloads each into public/img/<id>.jpg, and writes the list
// of successfully-downloaded ids to src/lib/localImages.ts. `unsplash()` then
// serves these locally (SafeImage still falls back to remote/gradient if a file
// is ever missing).
//
//   node scripts/fetch-images.mjs
//
import { promises as fs } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const SITE = path.join(ROOT, "src/lib/site.ts");
const OUT_DIR = path.join(ROOT, "public/img");
const MANIFEST = path.join(ROOT, "src/lib/localImages.ts");

const src = await fs.readFile(SITE, "utf8");
// Unsplash photo ids look like 1568901346375-23c9450c58cd or 1549611016-3a70d82b5040
const ids = [...new Set(src.match(/\d{6,}-[a-z0-9]{8,}/g) ?? [])];
console.log(`Found ${ids.length} unique image ids.`);

await fs.mkdir(OUT_DIR, { recursive: true });

const ok = [];
let done = 0;
async function grab(id) {
  const dest = path.join(OUT_DIR, `${id}.jpg`);
  try {
    // Skip if already downloaded and non-trivial.
    const st = await fs.stat(dest).catch(() => null);
    if (st && st.size > 5000) {
      ok.push(id);
      return;
    }
    const url = `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1280&q=80`;
    const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0 BurgerHouse/1.0" } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.byteLength < 5000) throw new Error(`too small (${buf.byteLength}b)`);
    await fs.writeFile(dest, buf);
    ok.push(id);
  } catch (err) {
    console.warn(`  ✗ ${id}: ${err.message}`);
  } finally {
    done++;
    if (done % 10 === 0) console.log(`  …${done}/${ids.length}`);
  }
}

// Limited concurrency.
const POOL = 6;
const queue = [...ids];
await Promise.all(
  Array.from({ length: POOL }, async () => {
    while (queue.length) await grab(queue.shift());
  }),
);

ok.sort();
const manifest = `// AUTO-GENERATED by scripts/fetch-images.mjs — do not edit by hand.
// Unsplash photo ids that have been downloaded to /public/img/<id>.jpg and are
// therefore served locally by unsplash() in site.ts.
export const LOCAL_IMAGE_IDS: readonly string[] = [
${ok.map((id) => `  "${id}",`).join("\n")}
];
`;
await fs.writeFile(MANIFEST, manifest, "utf8");
console.log(`\nDownloaded ${ok.length}/${ids.length} images → public/img`);
console.log(`Wrote ${MANIFEST}`);
